import type { CatchmentRow } from "../lib/types";

export function makeRow(overrides: Partial<CatchmentRow> = {}): CatchmentRow {
  return {
    climate_region: "Cold & Very Cold",
    urbanicity: "higher density urban",
    urbanicity_short: "HDU",
    catchment_type: "CBSA",
    catchment_code: "10000",
    catchment_label: "Cold & Very Cold HDU catchment 1 (demo)",
    population_2010: 2180000,
    housing_units_2010: 891000,
    population_density_sqmi: 8500,
    housing_unit_density_sqmi: 3570,
    housing_unit_coverage_percentile: 0.9,
    population_density_percentile: 0.9,
    population_coverage_percentile: 0.9,
    location_score: 0.9,
    selection_rank: 1,
    selected: true,
    station_distance_miles: 29.5,
    selected_station_name: "Cold HDU Climate Station 5 (demo)",
    selected_station_number: 730000,
    selected_station_lat: 44.09,
    selected_station_lon: -93.33,
    centroid_lat: 43.91,
    centroid_lon: -93.11,
    hourly_weather_qc_status: "INCOMPLETE",
    location_uniqueness_key: "CBSA:10000",
    scenario_score: 0.9,
    scenario_selected: true,
    scenario_rank: 1,
    nrel_filter_field: "in.metropolitan_and_micropolitan_statistical_area",
    nrel_filter_value: 10000,
    nrel_value_verified: true,
    nrel_verification_status: "VERIFIED",
    filter_scope_note: "Enumeration-verified demonstration mapping.",
    ...overrides,
  };
}
